version: "3.7"
services:
    splunk:
        image: splunk/splunk:7.2.6
        environment:
            - SPLUNK_START_ARGS=--accept-license --answer-yes
            - SPLUNK_PASSWORD=12345678
            - SPLUNK_ADD=tcp 1514
        volumes:
            - ./opt-splunk-etc:/opt/splunk/etc
            - ./opt-splunk-var:/opt/splunk/var
        ports:
            - 8000:8000
            - 1514:1514
        networks:
            - ecommerce_net

    jenkins:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - DOCKER_HOST=tcp://docker:2376
        volumes:
            - ./jenkins-data:/var/jenkins_home
        networks:
            - ecommerce_net
        ports:
            - 8080:8080
            - 50000:50000
    tomcat:
        image: tomcat:jdk8
        networks:
            - ecommerce_net
        ports:
            - 8888:8080

networks:
    ecommerce_net: